### ISSUE TITLE
ERROR: Failed to get runs from `runscanner server`

### ISSUE THREAD

**Issue by sklages** [miso-lims/miso-lims#2041]
Not sure if important:

I just upgraded `v0.2.182` -> `v0.2.186` -> `v0.2.187`. As far as I can see it worked smoothly.

In `miso_debug.log` I found an error message:
```
2019-08-20 07:43:30 ERROR: Failed to get runs from http://lammkarree:8088
org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Expected type float, integer, or string.; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Expected type float, integer, or string.
 at [Source: java.io.PushbackInputStream@83f2ed0; line: 1, column: 380] (through reference chain: ca.on.oicr.gsi.runscanner.dto.ProgressiveResponseDto["updates"]->java.util.ArrayList[0]->ca.on.oicr.gsi.runscanner.dto.IlluminaNotificationDto["startDate"])
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:240)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:225)
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:96)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:664)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:622)
	at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:389)
	at uk.ac.bbsrc.tgac.miso.webapp.service.RunScannerClient.scheduler(RunScannerClient.java:182)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Expected type float, integer, or string.
 at [Source: java.io.PushbackInputStream@83f2ed0; line: 1, column: 380] (through reference chain: ca.on.oicr.gsi.runscanner.dto.ProgressiveResponseDto["updates"]->java.util.ArrayList[0]->ca.on.oicr.gsi.runscanner.dto.IlluminaNotificationDto["startDate"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:1313)
	at com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer.deserialize(InstantDeserializer.java:218)
	at com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer.deserialize(InstantDeserializer.java:48)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:499)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:101)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:357)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:183)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:150)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:129)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:142)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:289)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:499)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:101)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:357)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2922)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:237)
	... 19 more
2019-08-20 07:43:31 INFO: FrameworkServlet 'miso': initialization started
```
I *think* I am running latest `run-scanner` (serving on `lammkarree`).. where can I see the version I am running?

**Comment by avarsava** [comment]
Hi sklages,

I'm sorry to hear you're seeing these errors from Run Scanner in your miso_debug.log. 

Currently there is no way to check your runscanner version from the front end; we'll be sure to add that as it would be useful information to have. If you have access to the files from which you built runscanner, you can check the <version> tag in 'pom.xml' to check which version you've deployed.

It looks as though there is a problem with the 'startDate' field coming from Run Scanner. Could you please open the JSON for a run on Run Scanner and show me what the 'startDate' field contains? (Here's instructions on how to access the run JSON: https://runscanner.readthedocs.io/en/latest/scanned/)

Please let me know if you have any issues gathering this information, or further questions about this error.

Regards,

Alexis

**Comment by sklages** [comment]
Hi Alexis,

Seems I am running:
```xml
   <name>Run Scanner</name>
   <version>1.5.0</version>
```

This is one of the latest runs:
```
{
[...]
 "containerModel":"S4",
 "laneCount":4,
 "healthType":"COMPLETED",
 "startDate":[2019,8,8,12,45,45],
 "completionDate":[2019,8,10,4,18,47],
 "pairedEndRun":true,
 "software":"Interop: v1.1.8 Instrument: 0",
[...]
 ```

 Another run on another machine:
 ```
{
[...]
"containerModel":"HiSeq 3000/4000 SR",
"laneCount":8,
"healthType":"COMPLETED",
"startDate":[2019,8,14,0,0],
"completionDate":[2019,8,15,10,37],
"pairedEndRun":false,
"software":"Interop: v1.1.8 Instrument: 0",
[...]
 ```

best,
Sven

**Comment by avarsava** [comment]
Hi Sven,

Thanks for providing me with this information. It looks as though you are running an outdated version of Run Scanner. With Run Scanner 1.6.2 we changed the format of the dates reported by Run Scanner, so MISO now expects this new format.

Would you be able to upgrade Run Scanner to the latest version (instructions here: https://runscanner.readthedocs.io/en/latest/installation/) and let me know if you continue to see this error?

Thanks,
Alexis

**Comment by sklages** [comment]
Now running latest release,
```
   <name>Run Scanner</name>
   <version>1.7.0</version>
```
It now reports:
```
{
[...]
  "containerModel" : "S4",
  "laneCount" : 4,
  "healthType" : "COMPLETED",
  "startDate" : "2019-08-08T10:45:45Z",
  "completionDate" : "2019-08-10T04:18:47Z",
  "pairedEndRun" : true,
  "software" : "Interop: v1.1.8 Instrument: 0",
[...]
```
just as expected. Seems the error is not showing up anymore :+1: 

thanks for the hint,
Sven
