### ISSUE TITLE
Error Creating Sample Classes

### ISSUE THREAD

**Issue by djcooke** [miso-lims/miso-lims#2203]
Reported by @usajusaj on Gitter. Can't create Sample Calsses via the UI due to below exception. This was on 0.2.197, but I reproduced on current develop branch as well.

```
2020-03-03 20:36:21 ERROR: 500 error handling REST request
org.springframework.dao.InvalidDataAccessApiUsageException: object references an unsaved transient instance - save the transient instance before flushing: uk.ac.bbsrc.tgac.miso.core.data.impl.SampleClassImpl; ne
sted exception is org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing: uk.ac.bbsrc.tgac.miso.core.data.impl.SampleClassImpl
        at org.springframework.orm.hibernate4.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:190)
        at org.springframework.orm.hibernate4.HibernateExceptionTranslator.convertHibernateAccessException(HibernateExceptionTranslator.java:57)
        at org.springframework.orm.hibernate4.HibernateExceptionTranslator.translateExceptionIfPossible(HibernateExceptionTranslator.java:44)
        at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:59)
        at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:209)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:147)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at uk.ac.bbsrc.tgac.miso.webapp.context.PrometheusInterceptor.invoke(PrometheusInterceptor.java:34)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:283)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671)
        at uk.ac.bbsrc.tgac.miso.persistence.impl.HibernateSampleClassDao$$EnhancerBySpringCGLIB$$8348bd93.getUsage(<generated>)
        at uk.ac.bbsrc.tgac.miso.service.impl.DefaultSampleClassService.collectValidationErrors(DefaultSampleClassService.java:174)
        at uk.ac.bbsrc.tgac.miso.service.impl.DefaultSampleClassService.collectValidationErrors(DefaultSampleClassService.java:38)
        at uk.ac.bbsrc.tgac.miso.service.AbstractSaveService.validateChange(AbstractSaveService.java:85)
        at uk.ac.bbsrc.tgac.miso.service.AbstractSaveService.create(AbstractSaveService.java:29)
        at uk.ac.bbsrc.tgac.miso.service.AbstractSaveService$$FastClassBySpringCGLIB$$ab5b2ae2.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:667)
        at uk.ac.bbsrc.tgac.miso.service.impl.DefaultSampleClassService$$EnhancerBySpringCGLIB$$53cac63e.create(<generated>)
        at uk.ac.bbsrc.tgac.miso.webapp.controller.rest.RestUtils.createObject(RestUtils.java:43)
        at uk.ac.bbsrc.tgac.miso.webapp.controller.rest.SampleClassRestController.createSampleClass(SampleClassRestController.java:58)
        at sun.reflect.GeneratedMethodAccessor426.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:854)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:765)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:209)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.filters.ExpiresFilter.doFilter(ExpiresFilter.java:1232)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at uk.ac.bbsrc.tgac.miso.webapp.context.RestSignatureFilter.checkFormLogin(RestSignatureFilter.java:138)
        at uk.ac.bbsrc.tgac.miso.webapp.context.RestSignatureFilter.doFilterInternal(RestSignatureFilter.java:96)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at uk.ac.bbsrc.tgac.miso.webapp.context.PrometheusCollectionFilter.doFilter(PrometheusCollectionFilter.java:39)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing: uk.ac.bbsrc.tgac.miso.core.data.impl.SampleClassImpl
        at org.hibernate.engine.internal.ForeignKeys.getEntityIdentifierIfNotUnsaved(ForeignKeys.java:249)
        at org.hibernate.type.EntityType.getIdentifier(EntityType.java:536)
        at org.hibernate.type.ManyToOneType.nullSafeSet(ManyToOneType.java:174)
        at org.hibernate.loader.Loader.bindPositionalParameters(Loader.java:1991)
        at org.hibernate.loader.Loader.bindParameterValues(Loader.java:1962)
        at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1897)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1858)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1838)
        at org.hibernate.loader.Loader.doQuery(Loader.java:906)
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:348)
        at org.hibernate.loader.Loader.doList(Loader.java:2550)
        at org.hibernate.loader.Loader.doList(Loader.java:2536)
        at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2366)
        at org.hibernate.loader.Loader.list(Loader.java:2361)
        at org.hibernate.loader.criteria.CriteriaLoader.list(CriteriaLoader.java:124)
        at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1623)
        at org.hibernate.internal.CriteriaImpl.list(CriteriaImpl.java:374)
        at org.hibernate.internal.CriteriaImpl.uniqueResult(CriteriaImpl.java:396)
        at uk.ac.bbsrc.tgac.miso.persistence.impl.HibernateProviderDao.getUsageBy(HibernateProviderDao.java:66)
        at uk.ac.bbsrc.tgac.miso.persistence.impl.HibernateSampleClassDao.getUsage(HibernateSampleClassDao.java:39)
        at uk.ac.bbsrc.tgac.miso.persistence.impl.HibernateSampleClassDao$$FastClassBySpringCGLIB$$c1e9f012.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
        ... 80 more
```

**Comment by djcooke** [comment]
I'll get a fix in for version 1.1.0. A work-around in the meantime would be to add Sample Classes via SQL:

```
SELECT userId INTO @user FROM User WHERE loginName = 'username';
INSERT INTO SampleClass(alias, sampleCategory, sampleSubcategory, dnaseTreatable, directCreationAllowed, suffix, v2NamingCode, createdBy, creationDate, updatedBy, lastUpdated)
VALUES ('Class Name', 'Aliquot', FALSE, TRUE, 'CN', 'CN', @user, NOW(), @user, NOW());
```

Notes:

* `sampleCategory` and `sampleSubcategory` must be values that appear in the dropdowns on the Create Sample Class page (or NULL for `sampleSubcategory` if not applicable)
* `suffix` is important if you use the `oicr` naming scheme; otherwise, it can be null
* `v2NamingCode` is important if you use the `v2` naming scheme; otherwise, it can be null
* after adding the sample class, you'll have to add relationships

View all sample classes (to get IDs):

```
SELECT * FROM SampleClass;
```

Add a relationship:

```
INSERT INTO SampleValidRelationship(parentId, childId, createdBy, creationDate, updatedBy, lastUpdated)
VALUES (1, 10, @user, NOW(), @user, NOW());
```

`parentId` and `childId` are the sample class IDs for the relationship.

Ensure that any relationships you add follow the rules detailed in the user manual as there will be no validation when adding them via SQL: https://miso-lims.readthedocs.io/projects/docs/en/latest/user_manual/type_data/#sample-classes-and-categories

**Comment by djcooke** [comment]
Fix is in PR: https://github.com/miso-lims/miso-lims/pull/2204

**Comment by usajusaj** [comment]
Thanks @djcooke !
