### ISSUE TITLE
flyway 5.2.4 outdated java 

### ISSUE THREAD

**Issue by mattihautameki** [miso-lims/miso-lims#2616]
Hi! 

I am installing an instance von MISO (release v1.39.1) following the baremetal method because docker/docker-compose is not supported in our environment (RedHat).
Sadly it seams like the jre version in flyway 5.2.4 is outdated. 
```
[root@wsps1125 flyway-5.2.4]# ./flyway -user=$MISO_DB_USER -password=$MISO_DB_PASS -url=$MISO_DB_URL -outOfOrder=true -locations=classpath:db/migration,classpath:uk.ac.bbsrc.tgac.miso.db.migration migrate -placeholders.filesDir=${MISO_FILES_DIR}
Flyway Community Edition 5.2.4 by Boxfuse
Database: jdbc:mariadb://localhost:3306/miso-p (MySQL 10.3)
Exception in thread "main" java.lang.UnsupportedClassVersionError: uk/ac/bbsrc/tgac/miso/db/migration/V0251__StatusXmlToRunTable$StatusValues has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.flywaydb.core.internal.util.ClassUtils.loadClass(ClassUtils.java:131)
	at org.flywaydb.core.internal.scanner.classpath.ClassPathScanner.scanForClasses(ClassPathScanner.java:105)
	at org.flywaydb.core.internal.scanner.Scanner.<init>(Scanner.java:66)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1689)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1356)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:161)
	at org.flywaydb.commandline.Main.main(Main.java:108)
```
I look at your docker images but could not find a hint on where to change the jre version so i remove the included java binary from flyway so the flyway script uses the one installed on the system.

In my case this is 
```
[root@wsps1125 flyway-5.2.4]# java -version
openjdk version "11.0.13" 2021-10-19 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.13+8-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.13+8-LTS, mixed mode, sharing)
```
In this case at least it did not complain about the java class version but refused to do the migrations because of a syntax error. 
```
[root@wsps1125 flyway-5.2.4]# ./flyway -user=$MISO_DB_USER -password=$MISO_DB_PASS -url=$MISO_DB_URL -outOfOrder=true -locations=classpath:db/migration,classpath:uk.ac.bbsrc.tgac.miso.db.migration migrate -placeholders.filesDir=${MISO_FILES_DIR}
Flyway Community Edition 5.2.4 by Boxfuse
Database: jdbc:mariadb://localhost:3306/miso-p (MySQL 10.3)
Executing SQL callback: beforeValidate
Successfully validated 167 migrations (execution time 00:00.398s)
Executing SQL callback: beforeMigrate
Creating Schema History table: `miso-p`.`flyway_schema_history`
WARNING: DB: Name 'flyway_schema_history_pk' ignored for PRIMARY key. (SQL State: 42000 - Error Code: 1280)
Current version of schema `miso-p`: << Empty Schema >>
WARNING: outOfOrder mode is active. Migration of schema `miso-p` may not be reproducible.
Migrating schema `miso-p` to version 0001 - base schema
Migrating schema `miso-p` to version 0002 - miso type data
Migrating schema `miso-p` to version 0003 - change logs
Migrating schema `miso-p` to version 0004 - boxes
ERROR: Migration of schema `miso-p` to version 0004 - boxes failed! Please restore backups and roll back database and code!
ERROR: 
Migration V0004__boxes.sql failed
---------------------------------
SQL State  : 42000
Error Code : 1064
Message    : (conn=30) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''box_position_seq') WHERE boxPositionId IS NULL' at line 1
Location   : db/migration/V0004__boxes.sql (/opt/miso/flyway-5.2.4/file:/opt/miso/flyway-5.2.4/jars/sqlstore-1.39.1.jar!/db/migration/V0004__boxes.sql)
Line       : 88
Statement  : UPDATE Sample set boxPositionId = nextval('box_position_seq') WHERE boxPositionId IS NULL
```

Can the mariadb version cause a problem here?

Best regards,
matti

**Comment by mattihautameki** [comment]
Hi! 

I just tested with mysql 5.7 and the migrations worked with a recent version of java. 
Do you have any plans on migration the system to a more recent version of mysql or mariadb ?

Best regards,
matti

**Comment by djcooke** [comment]
Hello,

We currently support MySQL 5.7 and MariaDB 10.2. I just tested with MariaDB 10.3 and saw the same error that you reported, so that version is definitely not yet supported. We will migrate to MySQL 8 and a more recent MariaDB at some point, hopefully within the next few months.

Your work-around for using Java 11 with Flyway 5.2.4 is the same approach that we would currently recommend. We plan to create a stand-alone migration tool in the future to simplify the migration process and avoid having to set up Flyway.

**Comment by mattihautameki** [comment]
Thank you very much for the clarification!
