### ISSUE TITLE
Jira integration not populating or fetching records

### ISSUE THREAD

**Issue by jayramr** [miso-lims/miso-lims#2640]
Hello, 

I'm trying to integreate jira via  HTTP Basic Auth config. 

I updated the details over the miso properties file and after restarted the service. 

By the way I'm currently using the docker version of miso. Please guide where do i can check whether the jira is successfully fetched or not? Please advise 

Thanks
Jayaram

**Comment by jayramr** [comment]
Updated below parameters
===
# miso.issuetracker.tracker:jira
# miso.issuetracker.jira.baseUrl:https://jira.example.com
# miso.issuetracker.jira.httpBasicAuthUsername:
# miso.issuetracker.jira.httpBasicAuthPassword:

I verified that I'm able to login with the credentials without any issues .

**Comment by djcooke** [comment]
There is JIRA integration on the [Edit Project](https://miso-lims.readthedocs.io/projects/docs/en/latest/user_manual/projects/#tracked-issues) and [Edit Run](https://miso-lims.readthedocs.io/projects/docs/en/latest/user_manual/sequencer_runs/#related-issues) pages. The easiest way to test would be to create a ticket and add a label matching the shortname of one of your projects, then check the Edit Project page to see if it shows up. You can also check the metrics endpoint (https://your.miso.server/metrics) and see if there are any JIRA failures at `miso_jira_issue_manager_errors` (this endpoint is meant for monitoring via Prometheus, but it is plain text that is fairly human-friendly). If you find that there are JIRA errors, you'll want to check the log at `/storage/miso/log/miso_debug.log` on the webapp container for more details

**Comment by jayramr** [comment]
Thanks @djcooke  for the pointer
From the metrics page -> "miso_jira_issue_manager_errors 0.0" 

I created a test ticket on jira portal and i clicked on Projects under preperation , but nothing listed. Is there any logs can i check whether this integration success of not. From the metrics page i can see only above value.

As per the expectation whatever tickets I'm creating on jira portal as a miso user should be reflect on the "Projects" path or in "run" path, please correct me if I'm wrong.

Also the "Edit run" page was this located below Intrument runs under Sequencing?  Please advise

**Comment by djcooke** [comment]
It sounds like you were on the Projects list page? To test JIRA integration, you need to

* create a project and give it a short name
* create a JIRA ticket and add a label that matches the project's short name
* check the Edit Project page (go to the Projects list and click on the project to get there)

Please check the user manual links I posted above for more information on these pages and how the tickets are linked to them

**Comment by jayramr** [comment]
@djcooke thanks for the guidance.

I followed the same way, but i can see the logs on /storage/miso/log/miso_debug.log

And this miso_jira_issue_manager_errors 7.0 

I have verified the login by accessing the jira portal over a browser and created and viewed the ticket . Please advise 

My jira version -> v6.3.12
Also I added this user account in the "jira-users" group. Do I need to update/add this user to admin/developers group ?


2022-03-01 19:13:28 INFO: FrameworkServlet 'miso': initialization completed in 50 ms
2022-03-02 06:16:11 ERROR: Error retrieving issues
java.io.IOException: Unable to get resource
	at uk.ac.bbsrc.tgac.miso.webapp.service.integration.jira.JiraIssueManager.retrieveList(JiraIssueManager.java:171) ~[classes/:?]
	at uk.ac.bbsrc.tgac.miso.webapp.service.integration.jira.JiraIssueManager.getIssuesByTag(JiraIssueManager.java:111) ~[classes/:?]
	at uk.ac.bbsrc.tgac.miso.webapp.controller.view.EditProjectController.lambda$setupForm$0(EditProjectController.java:103) ~[classes/:?]
	at uk.ac.bbsrc.tgac.miso.webapp.util.MisoWebUtils.addIssues(MisoWebUtils.java:255) [classes/:?]
	at uk.ac.bbsrc.tgac.miso.webapp.controller.view.EditProjectController.setupForm(EditProjectController.java:103) [classes/:?]
	at uk.ac.bbsrc.tgac.miso.webapp.controller.view.EditProjectController.setupForm(EditProjectController.java:95) [classes/:?]
	at uk.ac.bbsrc.tgac.miso.webapp.controller.view.EditProjectController$$FastClassBySpringCGLIB$$eeb9928e.invoke(<generated>) [classes/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736) [spring-aop-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at uk.ac.bbsrc.tgac.miso.webapp.context.PrometheusInterceptor.monitor(PrometheusInterceptor.java:48) [classes/:?]
	at uk.ac.bbsrc.tgac.miso.webapp.context.PrometheusInterceptor.invoke(PrometheusInterceptor.java:31) [classes/:?]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671) [spring-aop-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at uk.ac.bbsrc.tgac.miso.webapp.controller.view.EditProjectController$$EnhancerBySpringCGLIB$$d3f74ee0.setupForm(<generated>) [classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) [spring-web-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) [spring-web-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) [spring-webmvc-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:854) [spring-webmvc-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:765) [spring-webmvc-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) [spring-webmvc-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) [spring-webmvc-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) [spring-webmvc-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [spring-webmvc-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) [spring-webmvc-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655) [servlet-api.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) [spring-webmvc-4.3.24.RELEASE.jar:4.3.24.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) [servlet-api.jar:4.0.FR]

**Comment by djcooke** [comment]
You might be using an older version of JIRA than we've tested with. Can you try this in your browser?

1. Navigate to JIRA
2. Log in as the user you're configuring MISO to use
3. In the same browser, enter the URL `https://your.jira.server/rest/api/2/search?jql=labels=PROJ`, replacing `your.jira.server` with the same base URL you're configuring, and replacing `PROJ` with your project's short name

You should get a JSON response that includes the issues you expect to find

**Comment by jayramr** [comment]
[jira_debug.txt](https://github.com/miso-lims/miso-lims/files/8170401/jira_debug.txt)

@djcooke i uploaded the json reponse, please confirm if this fine or not. 

Or if my running jira version is not compatable, please suggest what is the best/stable jira version which support miso?

Thanks
Jay

**Comment by djcooke** [comment]
The response from JIRA looks good and should be compatible with MISO.

Is there any more to the stack trace that you posted above from `miso_debug.log`? It may be quite long with several "Caused by ..." blocks. This would be helpful for further troubleshooting

**Comment by jayramr** [comment]
[miso_debug.txt](https://github.com/miso-lims/miso-lims/files/8171396/miso_debug.txt)

@djcooke here you go. Please analyse and let me know . Updated the complete miso_debug.txt file.

**Comment by djcooke** [comment]
It looks like your JIRA server is using a self-signed certificate, which MISO won't accept. The best (most secure) solution is to add the certificate to the Java keystore on the webapp machine. To test this:

* download the certificate from JIRA
* mount/copy the certificate to your webapp machine
* on your webapp machine, run something like the below, replacing the parts in `<>` as appropriate:

`keytool -importcert -file <certificate-file> -keystore /usr/local/openjdk-11/lib/security/cacerts -alias <human-friendly-certificate-name>`

This will apply the certificate once and you'd have to do it again whenever the container is re-created (upgrading to new versions, etc.). Assuming this solution works, we can probably modify the image to automate this.

**Comment by jayramr** [comment]
@djcooke thanks for your suggestions.

I tried to export the certificate and tried to update this using the below command

keytool -importcert -file certificate.crt -keystore /usr/local/openjdk-11/lib/security/cacerts -alias jira_miso_lims
Warning: use -cacerts option to access cacerts keystore
Enter keystore password: ->> Not sure which password to pass here 

Please advise

**Comment by djcooke** [comment]
Keystore password will be "changeit" (default). Looks like the command I suggested above was for Java 8, and you need to use the `-cacerts` option starting with Java 9 (MISO uses Java 11). New command should be something like this:

`keytool -importcert -trustcacerts -cacerts -alias jira_miso_lims -file certificate.crt`

**Comment by jayramr** [comment]
@djcooke now no errors in miso_debug.log . Certificate successfully updated and no erros showing 
Also miso/metrics shows -> miso_jira_issue_manager_errors 0.0 

I restarted the webapp container multiple time and even rebooted the host. 

Then I accessed the Projects tab and still I'm unable to find the jira ticket label named "TESTLIMS" over Projects edit tab or Run tab. Not sure why this is missing for me. Any other logs for this to troubleshoot
![Uploading Screen Shot 2022-03-07 at 10.57.39 PM.png…]()

Please find the attached screenshots of jira and miso page
<img width="1593" alt="Screen Shot 2022-03-07 at 10 58 01 PM" src="https://user-images.githubusercontent.com/97015642/157099840-758b4ae6-806a-40f5-a8a0-5f9dffaad42f.png">

**Comment by djcooke** [comment]
The Tracked Issues section on the Edit Project page is collapsed by default. Click on the heading (should say "Tracked Issues" on the far right side - not visible in the screenshot) to expand and see if the ticket shows up there

**Comment by jayramr** [comment]
Hurray, thanks for the catch :) 

<img width="1507" alt="Screen Shot 2022-03-07 at 11 15 41 PM" src="https://user-images.githubusercontent.com/97015642/157102432-53e3885d-f7a5-4544-bd4e-bf2c25dd65bd.png">

Now the jira ticket reflecting properly. Feel feel to archive this ticket and please update the mentioned issues in the next release.

Questions
===

1) For production which mode of deployment is perfect? Baremetal or docker-compose, because I'm happy with docker based installation, as the baremetal seems to be more complex for me. 

If I opt for docker-compose, can i expect the (docker images)product releases in regular intervals? Please advise. 

2) Can I integrate the Single sign on (shiboleth ) authentication for the user management? or it only supports LDAP? Please advise. 

Please advise .

**Comment by djcooke** [comment]
1. There are pros and cons to each. If you find docker-compose easiest, I recommend sticking with that for now. That might work well for you forever, but if if at some point you end up with a lot of projects/samples/users and performance starts to degrade, it shouldn't be difficult to move to a different model (bare metal, Kubernetes, etc.). We normally release new Docker images at the same time as we make the official MISO releases, so you'll be able to get the same updates either way.

2. MISO currently only supports authentication via database (MISO stores credentials in its own database), LDAP, or AD. We are currently looking into supporting SAML and ADFS. This may end up being compatible with Shiboleth as well, but I am not familiar enough with it to say. Keep an eye on the release notes for more info when we've implemented this

We'll keep this ticket open as a request to automate injecting the certificate so you don't need to redo that whenever the container is re-created

**Comment by jayramr** [comment]
Dear Team,

Please advise this injecting certification on container is fixed? 
In addition What is the best upgrade miso one version to another in docker-compose way?

I follow below steps.
---
Taking the mysqldump from the exisitng setup
Destroy all containers 
Create container from scratch 
Then restore the database and restart 
Then injecting the certificate for jira lookup
--

Please advise if this is the correct approach ?

Thanks
Jay

**Comment by djcooke** [comment]
We have not made any changes related to this issue, but we will post an update here when we do. Please note that this is not a high priority, and we do not have an estimate for when it will be completed.

Your procedure for updating looks good. Just make sure you're updating/pulling the tag/version. You can verify the version in use at the bottom of the page in MISO

**Comment by jayramr** [comment]
Thanks @djcooke for your update.
