### ISSUE TITLE
new install database migration problems

### ISSUE THREAD

**Issue by jdkruzr** [miso-lims/miso-lims#2652]
Hi,

I am having a hell of a time getting a new installation of MISO running on Ubuntu 20.04 using the "baremetal" installation instructions, all centered around issues while running flyway.

First I discovered that this "nondeterministic function" problem had to be corrected before I could continue: https://stackoverflow.com/questions/26015160/deterministic-no-sql-or-reads-sql-data-in-its-declaration-and-binary-logging-i

Then I found the installation could not proceed beyond version 0170. I can no longer get Flyway to generate the original error, it now just dumps out saying it sees a previous migration attempt failed. How do I proceed from here? Is there a way to just concatenate everything in all migrations and then at the end produce a template for the correct current database schema?

Thanks.

```
miso@miso:~/flyway-5.2.4$ ./flyway -user=tgaclims -password=tgaclims -url=jdbc:mysql://localhost:3306/lims -outOfOrder=true -locations=classpath:db/migration,classpath:uk.ac.bbsrc.tgac.miso.db.migration -placeholders.filesDir=/storage/miso/files/ migrate
Flyway Community Edition 5.2.4 by Boxfuse
Thu Apr 21 14:31:15 UTC 2022 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
Database: jdbc:mysql://localhost:3306/lims (MySQL 8.0)
Executing SQL callback: beforeValidate
Thu Apr 21 14:31:16 UTC 2022 WARN: Caught while disconnecting...

EXCEPTION STACK TRACE:



** BEGIN NESTED EXCEPTION **

javax.net.ssl.SSLException
MESSAGE: closing inbound before receiving peer's close_notify

STACKTRACE:

javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
        at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:838)
        at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:817)
        at com.mysql.cj.protocol.a.NativeProtocol.quit(NativeProtocol.java:1313)
        at com.mysql.cj.NativeSession.quit(NativeSession.java:182)
        at com.mysql.cj.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:1743)
        at com.mysql.cj.jdbc.ConnectionImpl.close(ConnectionImpl.java:717)
        at org.flywaydb.core.internal.jdbc.JdbcUtils.closeConnection(JdbcUtils.java:97)
        at org.flywaydb.core.internal.database.base.Connection.close(Connection.java:161)
        at org.flywaydb.core.internal.database.base.Database.close(Database.java:488)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1731)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:1356)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:161)
        at org.flywaydb.commandline.Main.main(Main.java:108)


** END NESTED EXCEPTION **


ERROR: Validate failed: Detected failed migration to version 0170 (auto main)
```

**Comment by djcooke** [comment]
Hello,

It looks like you are using MySQL 8.0, which is not yet supported. Please use MySQL 5.7 instead.

If you get an error while running `flyway migrate`, you will be unable to migrate again ("Detected failed migration" error) without doing some manual cleanup/fixing first. Alternately, you can run `flyway clean` to delete all data from your database so that you can start over.

Please let us know if you have any issues running the migrations on MySQL 5.7

**Comment by jdkruzr** [comment]
Is there a reason to use 5.7.7 as noted in the instructions rather than 5.7.37 which appears to be the latest w/patches?

**Comment by djcooke** [comment]
The latest 5.7 patch is good. I'll update the documentation to reflect that

**Comment by jdkruzr** [comment]
Hi, I think MySQL 5.7 worked but can't tell for sure because it still dumps out with an error. It's also not clear what I should be connecting to to test it. Trying to browse to the site gets me a Tomcat 404, like this: https://miso.broken.works

Flyway output is as follows:

```
miso@miso:~/flyway-5.2.4$ ./flyway -user=tgaclims -password=tgaclims -url=jdbc:mysql://192.168.9.49:3306/lims?ssl=false -outOfOrder=true -
locations=classpath:db/migration,classpath:uk.ac.bbsrc.tgac.miso.db.migration -placeholders.filesDir=/storage/miso/files/ migrate
Flyway Community Edition 5.2.4 by Boxfuse
Fri Apr 22 14:28:25 UTC 2022 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
Database: jdbc:mysql://192.168.9.49:3306/lims (MySQL 5.7)
Executing SQL callback: beforeValidate
Successfully validated 170 migrations (execution time 00:00.460s)
Executing SQL callback: beforeMigrate
Current version of schema `lims`: 1370
WARNING: outOfOrder mode is active. Migration of schema `lims` may not be reproducible.
Schema `lims` is up to date. No migration necessary.
Executing SQL callback: afterMigrate
Fri Apr 22 14:28:29 UTC 2022 WARN: Caught while disconnecting...

EXCEPTION STACK TRACE:



** BEGIN NESTED EXCEPTION **

javax.net.ssl.SSLException
MESSAGE: closing inbound before receiving peer's close_notify

STACKTRACE:

javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
        at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:838)
        at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:817)
        at com.mysql.cj.protocol.a.NativeProtocol.quit(NativeProtocol.java:1313)
        at com.mysql.cj.NativeSession.quit(NativeSession.java:182)
        at com.mysql.cj.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:1743)
        at com.mysql.cj.jdbc.ConnectionImpl.close(ConnectionImpl.java:717)
        at org.flywaydb.core.internal.jdbc.JdbcUtils.closeConnection(JdbcUtils.java:97)
        at org.flywaydb.core.internal.database.base.Connection.close(Connection.java:161)
        at org.flywaydb.core.internal.database.base.Database.close(Database.java:488)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1731)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:1356)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:161)
        at org.flywaydb.commandline.Main.main(Main.java:108)
```

**Comment by jdkruzr** [comment]
Yes, it seems Flyway completed successfully.
You're right, nothing in /storage/miso/log.
No catalina.out in /var/lib/tomcat9 anywhere, as far as I can tell.
Nothing in localhost.<date>.log either.

I think CATALINA_HOME is /var/lib/tomcat9 as I have installed Tomcat from packages on Ubuntu 20.04?

**Comment by djcooke** [comment]
The Tomcat logs may be in a different location depending on the install. Maybe `/var/log/tomcat9/`?

**Comment by djcooke** [comment]
Closing due to inactivity. Please reopen if you require further assistance
