### ISSUE TITLE
MISO-Lims Baremetal Installation: Unable to obtain connection from database

### ISSUE THREAD

**Issue by YasirKusay** [miso-lims/miso-lims#2816]
Hi, 

I have followed your baremetal installation guide: https://miso-lims.readthedocs.io/projects/docs/en/latest/admin/baremetal-installation-guide/
but when performing the migration step ```./flyway ...```, I get this message.

```Unable to obtain connection from database (jdbc:mysql://localhost:3306 .......... for user 'administrator': Could not create connection to database server. Attempted reconnect 3 times. Giving up.```. 

Could you advise me on what I should do? The MySQL server is definitely running and I can connect to the lims database with the credentials I provided.

**Comment by YasirKusay** [comment]
I should add that I did manage to connect to the database directly using java, and I have configured the com.mysql.cj.jdbc.Driver driver

**Comment by YasirKusay** [comment]
Update 2:

If I use `-url="jdbc:mysql://localhost:3306/lims"`, I get a different error. The error message is ```The server time zone value 'ACST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.```

(ALSO, I AM CURRENTLY GETTING A SIMILAR ERROR WHEN RUNNING `startup.sh` inside `$CATALINA_HOME/bin/` inside the cataline log file.

I believe it may have to do with that url provided in the example.

I also added the location of the `com.mysql.cj.jdbc.Driver` driver class to `setenv.sh`.

**Comment by YasirKusay** [comment]
Update 3, I managed to partially get it working but the migration still failed. I got this error:

```
Database: jdbc:mysql://localhost:3306/lims (MySQL 8.0)
Exception in thread "main" java.lang.UnsupportedClassVersionError: uk/ac/bbsrc/tgac/miso/db/migration/V0251__StatusXmlToRunTable$StatusValues has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.flywaydb.core.internal.util.ClassUtils.loadClass(ClassUtils.java:131)
	at org.flywaydb.core.internal.scanner.classpath.ClassPathScanner.scanForClasses(ClassPathScanner.java:105)
	at org.flywaydb.core.internal.scanner.Scanner.<init>(Scanner.java:66)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1689)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1356)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:161)
	at org.flywaydb.commandline.Main.main(Main.java:108)
```

What version of connector j do you recommend?

**Comment by djcooke** [comment]
Hello. You shouldn't need to install or provide MySQL drivers anywhere.

If you are getting errors related to the time zone, ensure that you've configured the default time zone on your MySQL server (and restarted it to apply), and use the same URL parameters that we recommend in the setup guide. There are other ways to configure this that will work, but this is what we have found to work the best.

The `UnsupportedClassVersionError` is likely because your Flyway installation includes an older version of Java. You can delete the `jre` directory from your Flyway install to make it use whatever version you have set up instead. This should be 17+, which you should also have installed for Tomcat to use.

**Comment by YasirKusay** [comment]
Thanks for that, it is working now on localhost! However, is there a guide on how to set it up to work on a LAN as I would like to have a “demo” run.

**Comment by djcooke** [comment]
There is nothing special you need to do for MISO to work over a network. Assuming the default Tomcat config, and that nothing in your network is blocking access, you should be able to reach MISO using the server's IP address and port 8080. e.g. `http://192.168.0.1:8080` (if your MISO server's IP address were `192.168.0.1`). We usually use NGINX as a proxy to configure standard ports and SSL mainly because it's simpler than configuring the same via Tomcat. Some example NGINX configs can be found here: https://github.com/miso-lims/miso-lims/tree/develop/.docker/nginx

**Comment by sklages** [comment]
@YasirKusay - #2825 may help.

**Comment by sklages** [comment]
@YasirKusay - have you been able to solve this issue? If yes, how?
