### ISSUE TITLE
Update to MySQL 8.0.34: FlywaySqlException: Unable to obtain connection from database

### ISSUE THREAD

**Issue by sklages** [miso-lims/miso-lims#2823]
Maybe the same as #2816 ? Not sure as I did not find an explanation of what is initially going wrong :-)

I am running mysql 8.0.34.
I did a inplace update of mysql and reimported the sql dump just as described.

`mysqld --initialize --user=misoprj` to init database, user `root` was created.

Connecting on the command with `root` works just fine:

```
mysql -u root -p
Enter password:

Server version: 8.0.34 MySQL Community Server - GPL

mysql> ^DBye
```

Running `flyway` failed (repair, migrate or simply info):
```
MISO_DB_URL="jdbc:mysql://miso:3307/miso_seqcore?autoReconnect=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&sslMode=DISABLED&connectionTimeZone=SERVER&cacheDefaultTimeZone=false&useSSL=false"
MISO_FILES_DIR="/project/miso/current/storage/files/"

flyway \
      -X \
      -user=root \
      -password=XXXX \
      -url=${MISO_DB_URL} \
      -outOfOrder=true \
      -locations=classpath:db/migration,classpath:uk.ac.bbsrc.tgac.miso.db.migration \
      -placeholders.filesDir=${MISO_FILES_DIR} \
      info
```

Output:

```
DEBUG: Loading config file: /project/miso/2023/build_tools/flyway/5.2.4/conf/flyway.conf
DEBUG: Unable to load config file: /project/miso/home/flyway.conf
DEBUG: Unable to load config file: /project/miso/2023/build/flyway.conf
DEBUG: Using configuration:
DEBUG: flyway.jarDirs -> /project/miso/2023/build_tools/flyway/5.2.4/jars
DEBUG: flyway.outOfOrder -> true
DEBUG: flyway.locations -> classpath:db/migration,classpath:uk.ac.bbsrc.tgac.miso.db.migration
DEBUG: flyway.url -> jdbc:mysql://miso:3307/miso_seqcore?autoReconnect=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&sslMode=DISABLED&connectionTimeZone=SERVER&cacheDefaultTimeZone=false&useSSL=false
DEBUG: flyway.user -> root
DEBUG: flyway.placeholders.filesDir -> /project/miso/current/storage/files/
DEBUG: flyway.password -> ********
DEBUG: Adding location to classpath: /project/miso/2023/build_tools/flyway/5.2.4/drivers/derby-10.14.2.0.jar
DEBUG: Adding location to classpath: /project/miso/2023/build_tools/flyway/5.2.4/drivers/derbyclient-10.14.2.0.jar
DEBUG: Adding location to classpath: /project/miso/2023/build_tools/flyway/5.2.4/drivers/h2-1.4.197.jar
DEBUG: Adding location to classpath: /project/miso/2023/build_tools/flyway/5.2.4/drivers/hsqldb-2.4.1.jar
DEBUG: Adding location to classpath: /project/miso/2023/build_tools/flyway/5.2.4/drivers/mssql-jdbc-7.0.0.jre8.jar
DEBUG: Adding location to classpath: /project/miso/2023/build_tools/flyway/5.2.4/drivers/jtds-1.3.1.jar
DEBUG: Adding location to classpath: /project/miso/2023/build_tools/flyway/5.2.4/drivers/mysql-connector-java-8.0.12.jar
DEBUG: Adding location to classpath: /project/miso/2023/build_tools/flyway/5.2.4/drivers/jna-4.5.2.jar
DEBUG: Adding location to classpath: /project/miso/2023/build_tools/flyway/5.2.4/drivers/jna-platform-4.5.2.jar
DEBUG: Adding location to classpath: /project/miso/2023/build_tools/flyway/5.2.4/drivers/mariadb-java-client-2.3.0.jar
DEBUG: Adding location to classpath: /project/miso/2023/build_tools/flyway/5.2.4/drivers/postgresql-42.2.5.jre6.jar
DEBUG: Adding location to classpath: /project/miso/2023/build_tools/flyway/5.2.4/drivers/sqlite-jdbc-3.23.1.jar
DEBUG: Adding location to classpath: /project/miso/2023/build_tools/flyway/5.2.4/jars/sqlstore-2.1.0.jar
Flyway Community Edition 5.2.4 by Boxfuse
DEBUG: Memory usage: 33 of 2080M
ERROR: Unexpected error
org.flywaydb.core.internal.exception.FlywaySqlException:
Unable to obtain connection from database (jdbc:mysql://miso:3307/miso_seqcore?autoReconnect=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&sslMode=DISABLED&connectionTimeZone=SERVER&cacheDefaultTimeZone=false&useSSL=false) for user 'root': Could not create connection to database server. Attempted reconnect 3 times. Giving up.
---------------------------

SQL State  : 08001
Error Code : 0
Message    : Could not create connection to database server. Attempted reconnect 3 times. Giving up.

	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:60)
	at org.flywaydb.core.internal.database.DatabaseFactory.createDatabase(DatabaseFactory.java:72)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1670)
	at org.flywaydb.core.Flyway.info(Flyway.java:1521)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:167)
	at org.flywaydb.commandline.Main.main(Main.java:108)
Caused by: java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:902)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:827)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:207)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:433)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnection(DriverDataSource.java:399)
	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:56)
	... 5 more

Caused by: com.mysql.cj.exceptions.CJException: null,  message from server: "Host 'database.host' is not allowed to connect to this MySQL server"
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129)
	at com.mysql.cj.protocol.a.NativeProtocol.rejectProtocol(NativeProtocol.java:385)
	at com.mysql.cj.protocol.a.NativeProtocol.readServerCapabilities(NativeProtocol.java:512)
	at com.mysql.cj.protocol.a.NativeProtocol.beforeHandshake(NativeProtocol.java:397)
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1441)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:165)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:846)
	... 12 more
```

What is the difference? Why can I connect via `mysql` but not via `flyway`? What am I missing here?

**Comment by djcooke** [comment]
Are you running Flyway from the database server, or on a different machine? Your MySQL install likely doesn't allow remote access for the root user. Your options are

1. Recommended: Create a different MySQL user with sufficient privileges to use for Flyway. `GRANT ALL PRIVILEGES ON *.* TO 'username'@'host';` will include all of the necessary privileges. We have not investigated a minimal set of privileges
2. Allow remote root access to MySQL
3. Run Flyway from the database server

**Comment by sklages** [comment]
ok, thanks.

I chose (1) and it seems to work. 
```sql
CREATE USER 'root'@'dbserver.domain.tld' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'dbserver.domain.tld';
```

Interestingly (3) I am logged in at 'dbserver.domain.tld' and ran `flyway` there ... which resulted in the error.

I leave this issue open until I completed the db migration ...

**Comment by sklages** [comment]
flyway worked fine:
```
Successfully repaired schema history table `miso_seqcore`.`flyway_schema_history`.
Successfully applied 2 migrations to schema `miso_seqcore`.
``` 
thanks for the hint 👍
