### ISSUE TITLE
Failed to start component [Connector[AJP/1.3-8809]] | Unknown default host [miso] for service [StandardService[Catalina]]

### ISSUE THREAD

**Issue by sklages** [miso-lims/miso-lims#2825]
After successfully migrating to MySQL 8 (flybase was working fine, see #2823) I ran into a problem after compiling/deploying version `2.1.0`. (I didn't want to jump from `v1.56` directly to the latest version).

#### Apache Tomcat/9.0.71 - HTTP Status 404 – Not found
```
Description: The origin server did not find a current representation for
the target resource or is not willing to disclose that one exists.
```

#### catalina.2023-10-03.log
```
<...>
03-Oct-2023 08:00:41.068 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/project/miso/2023/tomcat-9.0.71/webapps/manager]
03-Oct-2023 08:00:41.085 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/project/miso/2023/tomcat-9.0.71/webapps/manager] has finished in [17] ms
03-Oct-2023 08:00:41.087 SEVERE [main] org.apache.catalina.mapper.MapperListener.findDefaultHost Unknown default host [miso] for service [StandardService[Catalina]]. Tomcat will not be able process HTTP/1.0 requests that do not specify a host name.
03-Oct-2023 08:00:41.088 SEVERE [main] org.apache.catalina.mapper.MapperListener.findDefaultHost Unknown default host [miso] for service [StandardService[Catalina]]. Tomcat will not be able process HTTP/1.0 requests that do not specify a host name.
03-Oct-2023 08:00:41.089 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-141.14.16.247-8088"]
03-Oct-2023 08:00:41.100 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["https-jsse-nio-141.14.16.247-8443"]
03-Oct-2023 08:00:41.102 SEVERE [main] org.apache.catalina.util.LifecycleBase.handleSubClassException Failed to start component [Connector[AJP/1.3-8809]]
	org.apache.catalina.LifecycleException: Protocol handler start failed
		at org.apache.catalina.connector.Connector.startInternal(Connector.java:1076)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardService.startInternal(StandardService.java:447)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:347)
		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:478)
	Caused by: java.lang.IllegalArgumentException: The AJP Connector is configured with secretRequired="true" but the secret attribute is either null or "". This combination is not valid.
		at org.apache.coyote.ajp.AbstractAjpProtocol.start(AbstractAjpProtocol.java:267)
		at org.apache.catalina.connector.Connector.startInternal(Connector.java:1073)
		... 12 more
03-Oct-2023 08:00:41.103 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [35739] milliseconds
```

#### miso_access_log.2023-10-03.txt
```
SERVER-IP - - [03/Oct/2023:07:58:43 +0200] "GET /miso/mainMenu HTTP/1.1" 404 693
SERVER-IP - - [03/Oct/2023:07:58:43 +0200] "GET /favicon.ico HTTP/1.1" 404 693
SERVER-IP - - [03/Oct/2023:07:58:51 +0200] "GET / HTTP/1.1" 404 693
SERVER-IP - - [03/Oct/2023:07:59:11 +0200] "GET / HTTP/1.1" 404 693
SERVER-IP - - [03/Oct/2023:08:00:41 +0200] "GET / HTTP/1.1" 404 693
SERVER-IP - - [03/Oct/2023:08:15:01 +0200] "GET /miso HTTP/1.1" 404 693
```

This again is probably a simple configuration issue.
I took over the configuration of our **mysql-5.7/v1.56** MISO production system, so I am wondering, what is different now?

#### the main issues?
- `Unknown default host [miso] for service [StandardService[Catalina]]`
- `Failed to start component [Connector[AJP/1.3-8809]]`

Any hints are highly appreciated :-)

**Comment by djcooke** [comment]
This isn't something I've seen before, but seems related to virtual host config. Do you have multiple virtual hosts configured in Tomcat?

With a default Tomcat setup, your context config files (`ROOT.xml` for MISO) should be in `.../conf/Catalina/localhost/`. I'm only guessing, but if you have a different directory under `.../conf/Catalina/` that doesn't match up with a virtual host, that may cause a problem

**Comment by sklages** [comment]
hmm, it is the same config as for our production system (v1.56, mysql 5.7). There I have no problems. 

I have added `secretRequired="false"` in AJP connector definition in `server.xml`:
```
<Connector address="miso" port="8809" protocol="AJP/1.3" redirectPort="8443" secretRequired="false" />
```
This prevents the actual failure, MISO starts as usual. This was not necessary in version prior to 2.x .. any idea why?

**Comment by sklages** [comment]
okay, I havent't touched this connector since its initial configuration ages ago :-) Now I simply disabled it, MISO starts just fine.
